config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :tasks
  resources :task_tags, only: [:show]
  resources :users, except: [ :destroy, :index ]
  get "login" => "login#new"
  post "login" => "login#create"
  delete "logout" => "login#destroy"

  namespace :admin do
    resources :users
    root "users#index"
  end

  root "tasks#index"
  match '*path' => "application#render_404", via: [:get, :put, :post, :delete, :options]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user, optional: true
  attr_accessor :task_tag_ids
  has_many :task_tag_with_tasks, dependent: :delete_all
  has_many :task_tags, through: :task_tag_with_tasks
  
  validates_presence_of :title, :content
  default_scope { order(created_at: :desc) }
  scope :order_by_finish_time, -> { order(finish_time: :desc) }
  scope :order_by_priority, -> { order(priority: :desc) }
  scope :find_task_tags, -> ( task_id ){ includes(:task_tags).where(task_tags: { id: task_id }) }

  def self.get_search_tasks(search_status , search_word = nil)
    if search_status == "all" || search_status == nil
      tasks = self.all
    else
      tasks = self.where( status: search_status )
    end
    tasks = tasks.where( "title LIKE ? OR content LIKE ? ", "%#{search_word}%",  "%#{search_word}%" ) if search_word.present?
    tasks
  end  
end

app/models/task_tag.rb
class TaskTag < ApplicationRecord
  has_many :task_tag_with_tasks
  has_many :tasks, through: :task_tag_with_tasks
end

app/models/task_tag_with_task.rb
class TaskTagWithTask < ApplicationRecord
  belongs_to :task_tag
  belongs_to :task
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  has_many :tasks, dependent: :destroy
  has_secure_password
  scope :admins, -> { where(role: "admin") }

  validates_presence_of :name
  validates_uniqueness_of :name
  before_destroy :check_can_delete

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def admin?
    role == 'admin'
  end

  private

  def check_can_delete
    errors[:base] << "cannot delete submission that has already been paid"
    return false
  end
end

app/controllers/admin/task_tags_controller.rb
class Admin::TaskTagsController < ApplicationController
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :check_role

  def index
    @users = User.includes(:tasks).page(params[:page]).per(5)
  end

  def show
    @user = User.includes(:tasks).find_by_id(params[:id])
    @tasks = @user.tasks.page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user)
  end

  def destroy
    user_id = params[:id].to_i
    if current_user.id == user_id
      flash[:danger] = "請由其他管理員刪除本帳號"
      redirect_to admin_root_path
    else
      begin
        HandleUser::Destroy.new(user_id)
      rescue
        flash[:danger] = "最後一位 admin 不可刪除"
        redirect_to admin_users_path
      end
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :role)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActionView::Template::Error, :with => :view_error
  rescue_from NameError, :with => :name_error

  def view_error
    render file: "#{Rails.root}/public/500_view_error.html" , status: 500
  end

  def name_error
    render file: "#{Rails.root}/public/500_name_error.html" , status: 500
  end

  def render_404
    render file: "#{Rails.root}/public/404.html" , status: 404
  end

  def login?
    current_user.present?
  end

  private
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by_id(session[:user_id])
    end
  end

  def check_login
    if !login?
      redirect_to login_path
    end
  end

  def check_login_before_login_and_signup
    if login?
      redirect_to root_path
    end
  end
  

  def clear_session_and_cookies
    forget(@current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    Logout::ForgetUser.new(user)
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def remember(user)
    Login::RememberUser.new(user)
    session[:user_id] = user.id
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent.signed[:remember_token] = user.remember_token
  end

  def check_role
    if login? && current_user.role != "admin"
      redirect_to root_path
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_action :check_login, only: [:destroy]
  before_action :check_login_before_login_and_signup, only: [:new]

  def new
  end

  def create
    user = User.find_by_name(params[:user][:name])
    if user && user.authenticate(params[:user][:password])
      remember(user)
      redirect_to root_path
    else
      flash[:danger] = '輸入的名字錯誤或是密碼有誤' # Not quite right!
      render :new
    end
  end

  def destroy
    clear_session_and_cookies
    redirect_to login_path
  end

  private

  
end

app/controllers/task_tags_controller.rb
class TaskTagsController < ApplicationController
  def show
    @task_tag = TaskTag.find_by_id( params[:id] )
    @tasks = current_user.tasks.find_task_tags(@task_tag.id).get_search_tasks( params[:search_status], params[:search_word]).page(params[:page]).per(5)
    @task_tags = TaskTag.all
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :check_login

  def index
    @tasks = current_user.tasks.get_search_tasks( params[:search_status], params[:search_word]).page(params[:page]).per(5)
    @task_tags = TaskTag.all
  end

  def show
    find_task
  end

  def new
    @task = Task.new    
  end
  
  def create
    @task = Task.new( task_params )
    @task.user_id = current_user.id
    if @task.save
      params[:task][:task_tag_ids].each { |i| @task.task_tag_with_tasks.create( task_tag_id: i.to_i ) }
      redirect_to tasks_path, notice: "任務新增成功!"
    else
      render :new
    end
  end
  

  def edit
    find_task
  end

  def update
    find_task
    @task.update(task_params)
    redirect_to tasks_path, notice: "任務更新成功!"
  end
  

  def destroy
    find_task
    @task.destroy if @task
    redirect_to tasks_path, notice: "任務已刪除!"
  end

  private
  def find_task
    @task = Task.find_by_id(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :content, :status, :priority, :finish_time, :task_tag_ids => [])
  end
  
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_login_before_login_and_signup, only: [:new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      remember(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end
  
  def update
    @user = User.find_by_id(params[:id])
    @user.update(user_params)
    redirect_to user_path( @user )
  end
  
  def show
    @user = User.find_by_id(params[:id])
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
  
end

app/helpers/admin/task_tags_helper.rb
module Admin::TaskTagsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by_id(session[:user_id])
    elsif ( user_id = cookies.signed[:user_id] )
      user = User.find_by_id(user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user ||= User.find_by_id(cookies.permanent.signed[:user_id])
      end
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  
end

app/helpers/tasks_helper.rb
module TasksHelper

  def priority(task)
    if task.priority === 3
      "高"
    elsif task.priority === 2
      "中"
    else
      "低"
    end
  end
  
  def status(task)
    case task.status
    when "pending"
      "待處理"
    when "processing"
      "處理中"
    when "finished"
      "已處理"
    else
      "未分類"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<% content_for :title do %>
  編輯<%= @user.name %>資料
<% end %>
<%= render "partials/header" %>

<div class="container">
  <div class="back_btn_block">
    <%= link_to "返回", admin_root_path, class: "btn btn-primary" %>
  </div>

  <%= form_for(@user, url: "/admin/users/#{@user.id}", method: :patch )do |user| %>
    <div class="form-group">
      <%= user.label :name, "使用者姓名" %>
      <%= user.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= user.label :role, "權限" %>
      <%= user.text_field :role, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= user.label :password, "密碼" %>
      <%= user.text_field :password, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= user.label :password_confirmation, "確認密碼" %>
      <%= user.text_field :password_confirmation, class: "form-control" %>
    </div>

    <div class="form-group submit_btn_block">
      <%= user.submit class: "btn btn-primary" %>    
    </div>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<% content_for :title do %>
  後台管理
<% end %>
<%= render "partials/header" %>

<div class="container">
  <div class="add_new_user_block">
    <%= link_to "新增使用者",new_admin_user_path, class: "btn btn-primary" %>  
  </div>

  <div class="all_users_block">
    <table class="table table-striped table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">名字</th>
          <th scope="col">權限</th>
          <th scope="col">文章數</th>
          <th scope="col">編輯</th>
          <th scope="col">刪除</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <th scope="row"><%= link_to user.name, admin_user_path(user) %></th>
          <td><%= user.role %></td>
          <td><%= user.tasks.size %></td>
          <td><%= link_to "編輯", edit_admin_user_path(id: user.id) %></td>
          <td><%= link_to "刪除", admin_user_path(id: user.id), method: :delete %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <div class="page_number_block">
      <%= paginate @users %>
    </div>
  </div>
  
</div>

app/views/admin/users/new.html.erb
<% content_for :title do %>
  新增使用者資料
<% end %>
<%= render "partials/header" %>

<div class="container">
  <div class="back_btn_block">
    <%= link_to "註冊", new_user_path, class: "btn btn-primary" %>
  </div>
  
  <%= form_for(@user, url: "/admin/users" )do |user| %>
    <div class="form-group">
      <%= user.label :name, "使用者姓名" %>
      <%= user.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= user.label :role, "權限" %>
      <%= user.text_field :role, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= user.label :password, "密碼" %>
      <%= user.text_field :password, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= user.label :password_confirmation, "確認密碼" %>
      <%= user.text_field :password_confirmation, class: "form-control" %>
    </div>

    <div class="form-group submit_btn_block">
      <%= user.submit class: "btn btn-primary" %>    
    </div>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<% content_for :title do %>
  <%= @user.name %>管理
<% end %>
<%= render "partials/header" %>

<div class="container">
  <div class="back_btn_block">
    <%= link_to "返回", admin_root_path, class: "btn btn-primary" %>
  </div>

  <h3> <%= @user.name%> - <%= @user.role %> </h3>
  <p>
    總共: <%= @user.tasks.count %> 個工作項目
  </p>

  <div class="user_tasks_block">
    <table class="table table-striped table-hover">
      <thead class="thead-dark">
        <tr>
          <th style="width: 15%" scope="col">任務</th>
          <th style="width: 25%" scope="col">任務內容</th>
          <th style="width: 10%" scope="col">任務狀態</th>
          <th style="width: 15%" scope="col">優先順續</th>
          <th style="width: 20%" scope="col">完成時間</th>
          <th style="width: 8%" scope="col">編輯</th>
          <th style="width: 8%" scope="col">刪除</th>
        </tr>
      </thead>
      <tbody>
        <% @tasks.each do |task| %>
        <tr>
          <th scope="row"><%= task.title %></th>
          <td><%= task.content %></td>
          <td><%= task.status %></td>
          <td><%= task.priority %></td>
          <td><%= task.finish_time.strftime("%Y-%m-%d") %></td>
          <td><%= link_to "編輯", edit_task_path(id: task.id) %></td>
          <td><%= link_to "刪除", task_path(id: task.id), method: :delete %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <div class="page_number_block">
      <%= paginate @tasks %>
    </div>
  </div>

  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key%>">
      <%= value %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/login/new.html.erb
<% content_for :title do %>
  歡迎登入
<% end %>
<%= render "partials/header" %>

<div class="container">
  <div class="back_btn_block">
    <%= link_to "註冊", new_user_path, class: "btn btn-primary" %>
  </div>

  <%= form_for :user, url: "login" do |user| %>
    <div class="form-group">
      <%= user.label :name, "使用者姓名" %>
      <%= user.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= user.label :password, "密碼" %>
      <%= user.text_field :password, class: "form-control" %>
    </div>

    <div class="form-group submit_btn_block">
      <%= user.submit "登入", class: "btn btn-primary" %>    
    </div>
  <% end %>
</div>

app/views/partials/_header.html.erb
<div class="container-fluid banner">
  <header class="header container-fluid">
    <div class="container">
      <% if current_user %>
        <%= current_user.name %>
        <%= link_to t("user.logout"), logout_path(id: current_user ), method: :delete %>
        <% if current_user.admin? %>
          <%= link_to "返回前台", root_path, class: "#{ 'active' if controller_name == "tasks" }" %>
          <%= link_to "後台管理", admin_users_path, class: "#{ 'active' if controller_name == "users" }" %>
        <% end %>
      <% end %>
    </div>
  </header>

  <h1>
    <% if content_for?(:title) %>
      <%= yield(:title)%>
    <% else %>
      <%= t("index.mission_task") %>
    <% end %>
  </h1>
</div>

app/views/task_tags/show.html.erb
<%= render "partials/header"%>
<div class="search_form container">
  <%= form_tag("/", method: "get", class: "form-inline") do %>
    <div class="row">
        <%= label_tag( :search_status, "狀態：", class: "my-1 mr-2") %>
        <%= select_tag( :search_status, options_for_select( [["全部", "all"], ["待處理", "pending"], ["進行中", "processing"],["完成", "finished"]]) ,class: "custom-select my-1 mr-sm-2" )%>

        <%= label_tag(:search_word, "關鍵字：") %>
        <%= text_field_tag(:search_word,"", class: "form-control") %>

        <%= submit_tag("Search", class: "form-control") %>
    </div>
    <%= link_to "NEW Task", new_task_path, class: "btn" %>
  <% end %>
</div>

<div class="container">
  <div class="content row">
    <div class="task_tags_block col-1">
      <ul>
        <li><%= link_to "全部", root_path %></li>
        <% @task_tags.each do | task_tag | %>
          <li class="<%= 'active' if task_tag.id == @task_tag.id %>"><%= link_to task_tag.name, task_tag_path(task_tag) %></li>
        <% end %>
      </ul>
    </div>

    <div class="main_content_block col-10">
      <%= t('index.no_task') if @tasks.blank? %>
      <% @tasks.each do |task| %>
        <section class="single_task_block task_<%= task.id %> row">
          <div class="task_priority_block col-2">
            <p>
              重要：<%= priority(task) %> <br>
              <%= status(task) %>
            </p>
          </div>
          <div class="task_head_block col-3">
            <%= task.title %><br>
            <%= task.finish_time.strftime("%Y-%m-%d") %> 
          </div>
          <div class="task_content_block col-6">
            <p>
              <%= task.content %>
            </p>
          </div>
          <div class="handle_task_block col-1">
            <%= link_to "編輯", edit_task_path(id: task.id) %>
            <%= link_to "刪除", task_path(id: task.id), method: :delete %>
          </div>
        </section>
      <% end %>

      <div class="page_number_block">
        <%= paginate @tasks %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<div class="task_form_block container">
  <%= form_for @task do |task| %>
    <div class="form-group">
      <%= task.label :title, "任務名稱" %>
      <%= task.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= task.label :task_tag_ids, "任務標籤" %>
      <% TaskTag.all.each do |task_tag| %>
        <%= check_box_tag "task[task_tag_ids][]", task_tag.id, @task.task_tags.include?(task_tag), id: "task_tag_#{task_tag.id}" %>
        <%= label_tag "task_tag_#{ task_tag.id}", task_tag.name %>
      <% end %>
    </div>

    <div class="form-group">
      <%= task.label :content, "任務內容" %>
      <%= task.text_field :content, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= task.label :priority, "優先順序" %>
      <%= task.select(:priority,[["高", 3],["中", 2] ,["低", 1]], {} ,{ class: "form-control"}) %>
    </div>

    <div class="form-group">
      <%= task.label :status, "任務狀態" %>
      <%= task.select(:status,[["待處理","pending"],["處理中", "processing"] ,["已處理", "finished"]], {} ,{ class: "form-control"})  %>
    </div>

    <div class="form-group">
      <%= task.label :finish_time, "預計完成時間" %>
      <%= task.date_field :finish_time, class: "form-control" %>
    </div>
    <div class="form-group submit_btn_block">
      <%= task.submit class: "btn btn-primary" %>    
    </div>
  <% end %>
</div>

<style>
  
</style>

app/views/tasks/edit.html.erb
<% content_for :title do %>
  編輯任務
<% end %>

<%= render "partials/header"%>

<%= render "tasks/form" %>

app/views/tasks/index.html.erb
<%= render "partials/header"%>

<div class="search_form container">
  <%= form_tag("/", method: "get", class: "form-inline") do %>
    <div class="row">
        <%= label_tag( :search_status, "狀態：", class: "my-1 mr-2") %>
        <%= select_tag( :search_status, options_for_select( [["全部", "all"], ["待處理", "pending"], ["進行中", "processing"],["完成", "finished"]]) ,class: "custom-select my-1 mr-sm-2" )%>

        <%= label_tag(:search_word, "關鍵字：") %>
        <%= text_field_tag(:search_word,"", class: "form-control") %>

        <%= submit_tag("Search", class: "form-control") %>
    </div>
    <%= link_to "NEW Task", new_task_path, class: "btn" %>
  <% end %>
</div>


<div class="container">
  <div class="content row">
    <div class="task_tags_block col-1">
      <ul>
        <li class="active"><%= link_to "全部", root_path %></li>
        <% @task_tags.each do | task_tag | %>
          <li><%= link_to task_tag.name, task_tag_path(task_tag) %></li>
        <% end %>
      </ul>
    </div>

    <div class="main_content_block col-10">
      <%= t('index.no_task') if @tasks.blank? %>
      <% @tasks.each do |task| %>
        <section class="single_task_block task_<%= task.id %> row">
          <div class="task_priority_block col-2">
            <p>
              重要：<%= priority(task) %> <br>
              <%= status(task) %>
            </p>
          </div>
          <div class="task_head_block col-3">
            <%= task.title %><br>
            <%= task.finish_time.strftime("%Y-%m-%d") %> 
          </div>
          <div class="task_content_block col-6">
            <p>
              <%= task.content %>
            </p>
          </div>
          <div class="handle_task_block col-1">
            <%= link_to "編輯", edit_task_path(id: task.id) %>
            <%= link_to "刪除", task_path(id: task.id), method: :delete %>
          </div>
        </section>
      <% end %>

      <div class="page_number_block">
        <%= paginate @tasks %>
      </div>
    </div>
    
  </div>
</div>

app/views/tasks/new.html.erb
<% content_for :title do %>
  新增任務
<% end %>

<%= render "partials/header"%>

<%= render "tasks/form" %>

app/views/tasks/show.html.erb
<h1> Hello this is task page </h1>

<table>
  <thead>
    <tr>
      <td>任務</td>
      <td>任務內容</td>
      <td>任務狀態</td>
      <td>優先順係</td>
      <td>完成時間</td>
      <td>編輯</td>
      <td>刪除</td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @task.title %></td>
      <td><%= @task.content %></td>
      <td><%= @task.status %></td>
      <td><%= @task.priority %></td>
      <td><%= @task.finish_time %></td>
      <td><%= link_to "編輯", edit_task_path(id: @task.id) %></td>
      <td><%= link_to "刪除", task_path(id: @task.id), method: :delete %></td>
    </tr>
  </tbody>
</table>

<%= link_to "回首頁", tasks_path %>

app/views/users/new.html.erb
<% content_for :title do %>
  註冊帳號
<% end %>
<%= render "partials/header" %>

<div class="container">
  <div class="back_btn_block">
    <%= link_to "已有帳號",login_path, class: "btn btn-primary" %>
  </div>
  
  <%= form_for @user do |user| %>
  
    <div class="form-group">
      <%= user.label :name, "使用者姓名" %>
      <%= user.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= user.label :password, "密碼" %>
      <%= user.text_field :password, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= user.label :password_confirmation, "確認密碼" %>
      <%= user.text_field :password_confirmation, class: "form-control" %>
    </div>

    <div class="form-group submit_btn_block">
      <%= user.submit class: "btn btn-primary" %>    
    </div>
  <% end %>
</div>